version: "3"
services:
  app:
    image: syberslxt/hrconvert2:latest
    container_name: hrconvert2
    restart: always
    ports:
      - 9002:80
    volumes:
      - ./config.php:/var/www/html/HRProprietary/HRConvert2/config.php
      - ./files:/home/converter:rw
